from enum import Enum


class Stage(Enum):
    NEED_OPEN_BRACE = "NEED_OPEN_BRACE"
    NEED_NAME_KEY = "NEED_NAME_KEY"
    NEED_COLON_1 = "NEED_COLON_1"
    NEED_QUOTE_OPEN_FUNC_NAME = "NEED_QUOTE_OPEN_FUNC_NAME"
    NEED_FUNC_NAME = "NEED_FUNC_NAME"
    NEED_QUOTE_CLOSE_FUNC_NAME = "NEED_QUOTE_CLOSE_FUNC_NAME"
    NEED_COMMA = "NEED_COMMA"
    NEED_PARAMS_KEY = "NEED_PARAMS_KEY"
    NEED_COLON_2 = "NEED_COLON_2"
    NEED_PARAMS_OPEN = "NEED_PARAMS_OPEN"
    NEED_QUOTE_OPEN_ARG_KEY = "NEED_QUOTE_OPEN_ARG_KEY"
    NEED_ARG_KEY = "NEED_ARG_KEY"
    NEED_QUOTE_CLOSE_ARG_KEY = "NEED_QUOTE_CLOSE_ARG_KEY"
    NEED_ARG_COLON = "NEED_ARG_COLON"
    NEED_QUOTE_OPEN_ARG_VALUE = "NEED_QUOTE_ARG_OPEN_VALUE"
    NEED_ARG_VALUE = "NEED_ARG_VALUE"
    NEED_COMMA_OR_CLOSE = "NEED_COMMA_OR_CLOSE"
    NEED_CLOSE_OUTER = "NEED_CLOSE_OUTER"
    DONE = "DONE"
